name: keyvalut
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  local_auth: ^2.3.0
  local_auth_android: ^1.0.49
  local_auth_darwin: ^1.2.2
  permission_handler: ^12.0.0
  path: ^1.9.1
  provider: ^6.1.5
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  otp: ^3.0.2
  cryptography: ^2.6.2
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^9.2.4
  collection: ^1.17.2
  path_provider: ^2.1.5
  universal_html: ^2.2.4
  file_picker: ^10.1.2
  device_info_plus: ^11.4.0
  barcode: ^2.2.9
  mobile_scanner: ^6.0.10
  flutter_slidable: ^4.0.0
  fluttertoast: ^8.2.8
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  freerasp: ^7.0.0
  pin_code_fields: ^8.0.1
  flutter_quill: ^10.7.0
  argon2: ^1.0.1
  share_plus: ^11.0.0
  file_saver: ^0.2.14
  intl: ^0.19.0


  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
