class Credential {
  final int? id;
  final String title;
  final String? website;
  final String? email;
  final String username;
  final String password;

  Credential({
    this.id,
    required this.title,
    this.website,
    this.email,
    required this.username,
    required this.password,
  });

  // Convert a Credential into a Map
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'title': title,
      'website': website,
      'email': email,
      'username': username,
      'password': password,
    };
  }

  // Convert a Map into a Credential
  factory Credential.fromMap(Map<String, dynamic> map) {
    return Credential(
      id: map['id'],
      title: map['title'],
      website: map['website'],
      email: map['email'],
      username: map['username'],
      password: map['password'],
    );
  }

  // Convert a Credential to JSON (excluding id for export)
  Map<String, dynamic> toJson() => {
    'title': title,
    'website': website,
    'email': email,
    'username': username,
    'password': password,
  };

  // Create a Credential from JSON (id will be generated by the database)
  factory Credential.fromJson(Map<String, dynamic> json) => Credential(
    title: json['title'] ?? '',
    website: json['website'],
    email: json['email'],
    username: json['username'] ?? '',
    password: json['password'] ?? '',
  );

}

class credit_cards {
  final int? id;
  final String? bank_name;
  final String ch_name;
  final String card_number;
  final String expiry_date;
  final int ccv;

  credit_cards ({
    this.id,
    this.bank_name,
    required this.ch_name,
    required this.card_number,
    required this.expiry_date,
    required this.ccv,
})
}
