name: Build Debug APK
   on: [push]
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - uses: subosito/flutter-action@v2
         - run: flutter pub get && flutter build apk --debug
         - uses: actions/upload-artifact@v3
           with:
             name: app-debug.apk
             path: build/app/outputs/flutter-apk/app-debug.apk
