name: Build APK Variants
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Build Profile APK
        run: flutter build apk --profile

      - name: Build Release APKs
        run: flutter build apk --release --split-per-abi --analyze-size

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload Profile APK
        uses: actions/upload-artifact@v4
        with:
          name: app-profile
          path: build/app/outputs/flutter-apk/app-profile.apk

      - name: Upload Release APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release-*.apk
